[workspace]
resolver = "2"
members = ["server"]

[profile.release]
lto = "fat"
# codegen-units = 1
# panic = "abort"
# strip = true
# opt-level = 3 # 0, 1, 2, 3 or "s" for small or "z" for small + no loop vectorization.
