[config]
skip_core_tasks = true

[tasks.build_server]
cwd = "./server"
command = "cargo"
args = ["build", "--release"]

[tasks.build_client]
cwd = "./client"
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown", "--release"]

[tasks.build_bindings]
cwd = "./client"
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen" }

command = "wasm-bindgen"
args = [
    "--out-dir=./target-wasm-bindgen/release",
    "--target=web",
    "--no-typescript",
    "--weak-refs",
    "--reference-types",
    "target/wasm32-unknown-unknown/release/moose2_client.wasm"
]
dependencies = ["build_client"]

[tasks.build_bindings.condition]
files_modified = { input = ["./target/wasm32-unknown-unknown/release/*.wasm"], output = ["./target-wasm-bindgen/release/*"] }

[tasks.build]
dependencies = [
    "build_bindings",
    "build_server",
]

### DEBUG

[tasks.build_server_debug]
cwd = "./server"
command = "cargo"
args = ["build"]

[tasks.build_client_debug]
cwd = "./client"
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown"]

[tasks.build_bindings_debug]
cwd = "./client"
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen" }
command = "wasm-bindgen"
args = [
    "--out-dir=./target-wasm-bindgen/debug",
    "--target=web",
    "--no-typescript",
    "--debug",
    "--keep-debug",
    "--weak-refs",
    "--reference-types",
    "target/wasm32-unknown-unknown/debug/moose2_client.wasm"
]
dependencies = ["build_client_debug"]

[tasks.build_bindings_debug.condition]
files_modified = { input = ["./target/wasm32-unknown-unknown/debug/*.wasm"], output = ["./target-wasm-bindgen/debug/*"] }


[tasks.debug]
dependencies = [
    "build_bindings_debug",
    "build_server_debug",
]

[tasks.run_debug]
cwd = "./server"
command = "cargo"
args = ["run", "--"]
