[package]
name = "moose2"
authors = ["Anthony DeDominic"]
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2024"

[features]
serve_static = ["dep:actix-files"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
#rand = { version = "0.9", features = ["thread_rng"], default-features = false }
rand = { version = "0.8.5", features = ["std", "std_rng"], default-features = false }
base64 = { version = "0.22" }
png = "0.17.5"
crc32fast = "1.3.2"
maud = "0.23.0"
actix-web = "4.9"
actix-session = { version = "0.10", default-features = false, features = ["cookie-session"] }
percent-encoding = "2.1.0"
md5 = "0.7.0"
deadpool-sqlite = { version = "0.10.0", default-features = false, features = ["rt_tokio_1"] }
rusqlite = { version = "0.33.0", features = ["bundled", "time"] }
oauth2 = { version = "5", default-features = false, features = ["reqwest"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
bcrypt-pbkdf = "0.9.0"
futures = "0.3"
include_dir = "0.7.3"
const_format = "0.2.30"
clap = { version = "4.4.6", features = ["derive"] }
directories = "5.0.1"
tokio = { version = "1", default-features = false, features = ["rt", "time", "macros", "signal"] }
time = { version = "0.3.36", features = ["formatting", "parsing", "macros"] }

[dependencies.actix-files]
version = "0.6"
optional = true
